### ISSUE TITLE
problème fonction battery + bonus: docker

### ISSUE THREAD

**Issue by AAA97AAA** [unige-semantics-2017/minotaur#1]
Bonjour,

J'ai pas très bien compris qu'est-ce-que la fonction `battery` doivent faire.
Je pense avoir compris la fonction `winning` mais je ne comprends pas l'utilité de `battery.`

Vous dites que la fonction `battery` fait la relation entre la batterie d'un téléphone et un `Term.`
Est-ce-que j'ai bien compris:
  `battery` s'agit d'une fonction similaire à `winning` mais le `through` n'est pas un `path` complet ?
 
 On doit donc vérifier que `level` n'est pas `zero` après avoir effectué le nombre d'étape dans `through`?

Bonus: docker build : erreur: unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat Dockerfile: no such file or directory

Merci.

**Comment by saucisson** [comment]
`battery` verifie qu'il y a assez d'énergie dans la batterie pour éclairer au moins tout un chemin passé aussi en paramètre.
`winning` diffère car il faut aussi faire attention à aller d'une entrée à une sortie, en passant par le minotaur.

**Comment by AAA97AAA** [comment]
Pour la fonction `battery`:

Soit `val: Term` tel que `val = toNat(10)`.

Je souhaite accéder à la valeur précédent `toNat(10)`, ie. `toNat(9)` en utilisant` fresh { z in ...} `.

Cependant, j'ai un problème. J'ai essayé:

`val === succ(z)`
`val === ["succ": of]`

et plusieurs autres trucs, mais pas le bon. J'ai jeté un coup d'oeil sur les fichiers de LogicKit de Dimitri, et il semblait bien avoir utilisé `succ(z)` mais cela ne fonctionne pas.

**Comment by saucisson** [comment]
"ça ne fonctionne pas", c'est un peu vague. Il faut en effet utiliser `val === succ(z)`. As-tu testé ça sur un tout petit exemple ?

**Comment by AAA97AAA** [comment]
Le code compile correctement mais lors du test avec docker build, il affiche:

"Executed 6 tests, with 1 failure (0 unexpected)"

"error: minotaurTests.testBattery : XCTAssertEqual failed: ("0") is not equal to ("1") - number of paths is incorrect"

J'ai mis un print `level` dans mon implémentation (voir ci-dessous), lors de la première itération, il affiche bien correctement:
`["succ": ["succ": ["succ": ["succ": ["succ": ["succ": ["succ": 0]]]]]]]`

mais après, les nombres affichés sont du type `$N` avec N un nombre.

`func battery (through: Term, level: Term) -> Goal {
    print("level \(level)") // a enlever si fonctionne
    return  (through === List.empty) ||
            delayed (fresh { x in fresh { y in fresh { z in
              (through === List.cons(x, y)) &&
              (level ≡ succ(z)) &&
              (battery(through:y, level: z))

            }}})
}`

**Comment by saucisson** [comment]
Peux-tu poster ta réponse dans le ticket GitHub, s'il te plaît ?

**Comment by AAA97AAA** [comment]
En fait, j'ai supprimé la réponse, car je me suis rendu compte que ma fonction `battery` fonctionne mais que le problème vient de la fonction `path.`

Je vais essayer de refaire la fonction `path`

Merci
