### ISSUE TITLE
Problème test fonction battery

### ISSUE THREAD

**Issue by arthurdeschamps** [unige-semantics-2017/minotaur#4]
Le test de la fonction `battery` pour aller de la chambre (4,4) à la chambre (3,2) retourne une erreur quand la fonction ne trouve pas exactement 1 path. Or, il y a 2 paths pour faire ce chemin avec 7 unités de batterie.

**Comment by GiovannaTheo** [comment]
Effectivement, on peut y accéder par les deux chemins suivant: `(4,4) -> (3,4) -> (2,4) -> (2,3) -> (2,2)->(3,2)` et par `(4,4) -> (3,4) -> (2,4) -> (2,3) -> (1,3) -> (1,2) -> (2,2) -> (3,2)` où les 7 unités de batterie sont consommées.

**Comment by arthurdeschamps** [comment]
Oui du coup si on compte une unité pour chaque `room`, inclue le chambre de départ, ca ne marche pas

**Comment by saucisson** [comment]
On compte en effet la batterie pour chaque `room`.
