### ISSUE TITLE
Récupérer le successeur une seul fois

### ISSUE THREAD

**Issue by GiovannaTheo** [unige-semantics-2017/minotaur#5]
Bonjour,

L'implémentation de ma fonction batterie me retourne un path en trop car le level de ma batterie n'est pas diminué de 1 pour la première chambre (enfin je crois que c'est ça le problème..). Comment est-ce que je peux utiliser le successeur de level comme argument de la fonction à son appel ? J'ai essayé la méthode suivante:

```
func battery1(through: Term, level: Term) -> Goal{
   ...
}

func battery (through: Term, level: Term) -> Goal {
    return  battery1(through: through, level: succ(level))
}

```
Mais sans succès...

**Comment by saucisson** [comment]
Tu passes bien le sucesseur de `level` à `battery1`. Le problème doit se trouver ailleurs.

**Comment by GiovannaTheo** [comment]
En fait je me suis mal exprimé, je veux appeler `battery1 ` avec "level-1", du coup pas le successeur de `level` mais son prédécesseur.

**Comment by saucisson** [comment]
On a vu en séance d'exercices lundi comment décomposer une variable avec `===`...

**Comment by GiovannaTheo** [comment]
J'ai trouvé une autre solution en fait, pb résolu.
